config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, path: 'admin', controllers: {
    sessions: 'admin/sessions'
  }
  devise_for :experts, path: 'experts', controllers: {
    sessions: "experts/sessions"
  }
  devise_for :users, path: 'users', controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
   }

  resources :matches
  resources :users
  resources :experts
  resources :care_plans

  root to: "home#index"

  # the homepage for experts
  get '/dashboard', to: 'dashboard#index'

  #the homepage for users
  get '/user_home', to: 'home#user_home'

  #the homepage for admins
  get '/admin', to: 'admin#index'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_expert!
  helper_method :matches
  helper_method :care_plans

  def matches
    @matches ||= current_expert.matches
  end

  def care_plans
    current_expert.care_plans
  end
end

app/views/dashboard/index.html.erb
<%= link_to destroy_expert_session_path, method: :delete do %>Log out<% end %>
<br>
<br>
<h1>My Expert Dashboard</h1>
<hr>
<% if matches.empty? %>
  You do not currently have any matches.
  <%= current_expert %>
  <%= current_expert.id %>
<% else %>
  <h3>You've been matched with the following users: </h3>
  <% matches.each do |match| %>
    <%= match.user.email %>
    <%= link_to "Show Match", controller: "matches", action: "show", id: match.id %>
    <hr>
  <% end %>
<% end %>

<% care_plans.each do |plan| %>
  <%= plan.status %>
<% end %>