config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, path: 'admin', controllers: {
    sessions: 'admin/sessions'
  }
  devise_for :experts, path: 'experts', controllers: {
    sessions: "experts/sessions"
  }
  devise_for :users, path: 'users', controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
   }

  resources :matches
  resources :users
  resources :experts
  resources :care_plans

  root to: "home#index"

  # the homepage for experts
  get '/dashboard', to: 'dashboard#index'

  #the homepage for users
  get '/user_home', to: 'home#user_home'

  #the homepage for admins
  get '/admin', to: 'admin#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/care_plan.rb
class CarePlan < ApplicationRecord
  STATUS = ["independent", "interdependent", "dependent", "crisis", "grieving"]
  validates_presence_of :summary_of_care
  validates_presence_of :summary_of_goals
  validates :status, inclusion: {in: STATUS}
  belongs_to :expert
end

app/models/expert.rb
class Expert < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :matches
  has_many :users, through: :matches

  has_many :care_plans
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :expert
  belongs_to :user

  validates_uniqueness_of :user_id, scope: :expert_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!

  def index
    @matches = Match.all
    @users = User.all
    @experts = Expert.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/care_plans_controller.rb
class CarePlansController < ApplicationController
  helper_method :status_options
  helper_method :experts

  def index
    @care_plans = CarePlan.all
  end

  def new
    @care_plan = CarePlan.new
  end

  def create
    @care_plan = CarePlan.new(care_plan_params)
    if @care_plan.save
      redirect_to(care_plans_path, {notice: "care plan created"})
    else
      render :new
    end
  end

  private

  def care_plan_params
    params.require(:care_plan).permit(:summary_of_care, :summary_of_goals, :status, :expert_id)
  end

  def status_options
    CarePlan::STATUS
  end

  def experts
    Expert.all
  end
end

app/controllers/concerns/accessible.rb
module Accessible
  extend ActiveSupport::Concern
  included do
    # before_action :check_user
  end

  protected
  # def check_user
  #   if current_expert
  #     flash.clear
  #     redirect_to(dashboard_path) and return
  #   elsif current_user
  #     flash.clear
  #     # The authenticated root path can be defined in your routes.rb in: devise_scope :user do...
  #     redirect_to(user_home_path) and return
  #   end
  # end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_expert!
  helper_method :matches
  helper_method :care_plans

  def matches
    @matches ||= current_expert.matches
  end

  def care_plans
    current_expert.care_plans
  end
end

app/controllers/experts_controller.rb
class ExpertsController < ApplicationController
  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
  end

  def user_home
    @match = Match.find_by(user_id: current_user.id)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def show
    @match = Match.find(params[:id])
  end

  def edit
    @match = Match.find(params[:id])
  end

  def new
    @experts = Expert.all
    @users = User.all
    @match = Match.new
  end

  def create
    #TODO: use private params method and hidden id field in form
    @match = Match.new(user_id: params[:match][:user_id], expert_id: params[:match][:expert_id], id: (Match.count + 1))
    if @match.save
      flash[:notice] = "match saved"
      redirect_to admin_path
    else
      flash[:error] = "failed to save match"
      redirect_to new_match_path
    end
  end

  def destroy
    @match = Match.find(params[:id])
    @match.destroy
    redirect_to admin_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_user, only: :destroy
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render template: 'users/registrations/new'
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(email: params[:email])
    redirect_to user_path(@user)
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  private
  def user_params
    params.require(:user).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
  :user
end

def resource
  @resource ||= User.new
end

def devise_mapping
  @devise_mapping ||= Devise.mappings[:user]
end
end

app/views/admin/index.html.erb
<%= link_to destroy_admin_session_path, method: :delete do %>Log out<% end %>
<br>
<br>
<h1>My Admin Portal</h1>
<hr>
<h2>Matches</h2>
<%= link_to 'Create a Match', new_match_path %>
<% if @matches.nil? %>
  There are currently no matches.
<% else %>
  <table>
  <thead>
    <tr>
      <th>User</th>
      <th>Expert</th>
    </tr>
  </thead>
  <tbody>
    <% @matches.each do |match| %>
    <tr>
      <td><%= match.user.email %></td>
      <td><%= match.expert.email %></td>
      <td><%= link_to "Show", "/matches/#{match.id}" %></td>
      <td><%= link_to "Edit", "/matches/#{match.id}/edit" %></td>
      <td><%= link_to "Destroy", "/matches/#{match.id}", method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
      <% end %>
  </tbody>
  </table>
<% end %>
<hr>
<% if @users.nil? %>
  There are currently no users.
<% else %>
  <h2>Users</h2>
  <table>
  <thead>
    <tr>
      <th>Email Address</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= link_to "Show", "/users/#{user.id}" %></td>
      <td><%= link_to "Edit", "/users/#{user.id}/edit" %></td>
      <td><%= link_to "Destroy", "/users/#{user.id}", method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
      <% end %>
  </tbody>
  </table>
<% end %>
<hr>
<% if @experts.nil? %>
  There are currently no experts.
<% else %>
  <h2>Experts</h2>
  <table>
  <thead>
    <tr>
      <th>Email Address</th>
    </tr>
  </thead>
  <tbody>
    <% @experts.each do |expert| %>
    <tr>
      <td><%= expert.email %></td>
      <td><%= link_to "Show", "/experts/#{expert.id}" %></td>
      <td><%= link_to "Edit", "/experts/#{expert.id}/edit" %></td>
      <td><%= link_to "Destroy", "/experts/#{expert.id}", method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
      <% end %>
  </tbody>
  </table>
<% end %>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectGrayce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% unless flash.empty? %>
     <script type="text/javascript">
        <% flash.each do |f| %>
          <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
       	 toastr['<%= type %>']('<%= f[1] %>');
       <% end %>
     </script>
    <% end %>
    <%= yield %>
  </body>
</html>