config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, path: 'admin', controllers: {
    sessions: 'admin/sessions'
  }
  devise_for :experts, path: 'experts', controllers: {
    sessions: "experts/sessions"
  }
  devise_for :users, path: 'users', controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
   }

  resources :matches
  resources :users
  resources :experts
  resources :care_plans

  root to: "home#index"

  # the homepage for experts
  get '/dashboard', to: 'dashboard#index'

  #the homepage for users
  get '/user_home', to: 'home#user_home'

  #the homepage for admins
  get '/admin', to: 'admin#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
  end

  def user_home
    @match = Match.find_by(user_id: current_user.id)
  end
end

app/views/home/index.html.erb
<% if current_user || current_expert %>
	<%= link_to destroy_user_session_path, method: :delete do %>Log out<% end %>
<% end %>

<% if current_expert %>
	<%= link_to dashboard_path, class: 'login-button' do %>Go to Dashboard<% end %>
<% end %>


<h1> I am a: </h1>
<%= button_to 'User', user_home_path, method: :get %>
<%= button_to 'Expert', dashboard_path, method: :get %>

app/views/home/user_home.html.erb
<%= link_to destroy_user_session_path, method: :delete do %>Log out<% end %>
<br>
<br>
<h1>My User Dashboard</h1>
<hr>
<% if @match.nil? %>
  We're working on pairing you up.
<% else %>
  <h3>You've been matched with: </h3>
  <%= @match.expert.email %>
<% end %>