config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, path: 'admin', controllers: {
    sessions: 'admin/sessions'
  }
  devise_for :experts, path: 'experts', controllers: {
    sessions: "experts/sessions"
  }
  devise_for :users, path: 'users', controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
   }

  resources :matches
  resources :users
  resources :experts
  resources :care_plans

  root to: "home#index"

  # the homepage for experts
  get '/dashboard', to: 'dashboard#index'

  #the homepage for users
  get '/user_home', to: 'home#user_home'

  #the homepage for admins
  get '/admin', to: 'admin#index'
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :expert
  belongs_to :user

  validates_uniqueness_of :user_id, scope: :expert_id
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def show
    @match = Match.find(params[:id])
  end

  def edit
    @match = Match.find(params[:id])
  end

  def new
    @experts = Expert.all
    @users = User.all
    @match = Match.new
  end

  def create
    #TODO: use private params method and hidden id field in form
    @match = Match.new(user_id: params[:match][:user_id], expert_id: params[:match][:expert_id], id: (Match.count + 1))
    if @match.save
      flash[:notice] = "match saved"
      redirect_to admin_path
    else
      flash[:error] = "failed to save match"
      redirect_to new_match_path
    end
  end

  def destroy
    @match = Match.find(params[:id])
    @match.destroy
    redirect_to admin_path
  end
end

app/views/matches/new.html.erb
<%= link_to 'Back to Admin Portal', admin_path %>

<h3>Create a New Match:</h3>
<%= form_for :match ,:url=>{:action =>"create"} do |f| %>
  <%= f.label :expert %>
  <%= f.collection_select :expert_id, @experts, :id, :email %>
  <%= f.label :user %>
  <%= f.collection_select :user_id, @users, :id, :email %>
  <%= f.submit %>
<% end %>

app/views/matches/show.html.erb
<% if current_expert %>
  <%= link_to 'Back to Matches', dashboard_url %>
<% elsif current_admin %>
  <%= link_to 'Back to Admin Portal', admin_url %>
<% end %>

<h3>Expert:</h3>
<%= @match.expert.email %>
<h3>User:</h3>
<%= @match.user.email %>